// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcPanqxURWRsjHU67M8MSPcH6F4ak6Hg',
    appId: '1:597027203971:web:31024ac945630f68a664b6',
    messagingSenderId: '597027203971',
    projectId: 'jaymnjo',
    authDomain: 'jaymnjo.firebaseapp.com',
    storageBucket: 'jaymnjo.firebasestorage.app',
    measurementId: 'G-YM8NCGRQ27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKeirE84KIKY3DK5-oOBB3lowlleCphPY',
    appId: '1:597027203971:android:42db191bff65b2f7a664b6',
    messagingSenderId: '597027203971',
    projectId: 'jaymnjo',
    storageBucket: 'jaymnjo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJJIX9jEW4Vx43UyxJz8EQx1Kzl8_3TC4',
    appId: '1:597027203971:ios:6f36790c89e51b82a664b6',
    messagingSenderId: '597027203971',
    projectId: 'jaymnjo',
    storageBucket: 'jaymnjo.firebasestorage.app',
    iosClientId: '597027203971-9toa17i2cmdal4odloniflepqfvr631j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jaymnjoCpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJJIX9jEW4Vx43UyxJz8EQx1Kzl8_3TC4',
    appId: '1:597027203971:ios:6f36790c89e51b82a664b6',
    messagingSenderId: '597027203971',
    projectId: 'jaymnjo',
    storageBucket: 'jaymnjo.firebasestorage.app',
    iosClientId: '597027203971-9toa17i2cmdal4odloniflepqfvr631j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jaymnjoCpa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQcPanqxURWRsjHU67M8MSPcH6F4ak6Hg',
    appId: '1:597027203971:web:adb8f4e5c0c24921a664b6',
    messagingSenderId: '597027203971',
    projectId: 'jaymnjo',
    authDomain: 'jaymnjo.firebaseapp.com',
    storageBucket: 'jaymnjo.firebasestorage.app',
    measurementId: 'G-97VRBXJJDD',
  );

}